### PR TITLE
Fixed drivetrain ports and controller axis readings.

### LINKED ISSUE #3: Controls are inverted and flipped on the test robot
Tilting the forward axis on the controller makes the robot turn, and tilting the sideways axis on the controller makes the robot go forward or backward.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
**Summary**

* Mirrored the drivetrain ports between the left and right sides of the robot.
* Set the right motors to be inverted in direction.
* Mirrored the left/right axis on the controller.

Resolves #3

### CODE REVIEW

File: src/main/java/frc/robot/Ids.java [hunk 1]
```diff
@@ -4,10 +4,10 @@
     public static final int CONTROLLER_DRIVE_PORT = 0;
     public static final int CONTROLLER_OPERATOR_PORT = 0;
 
-    public static final int DRIVE_LEFT_LEAD_DEVICE = 1;
-    public static final int DRIVE_LEFT_FOLLOW_DEVICE = 2;
-    public static final int DRIVE_RIGHT_LEAD_DEVICE = 4;
-    public static final int DRIVE_RIGHT_FOLLOW_DEVICE = 3;
+    public static final int DRIVE_LEFT_LEAD_DEVICE = 3;
+    public static final int DRIVE_LEFT_FOLLOW_DEVICE = 4;
```
Comment (MackinnonBuck) [inline src/main/java/frc/robot/Ids.java:8]: Just noticed that switching these around might mean we don't have to do `rightMotors.setInverted()`. Let's test that before merging.

**Review by ToddFerris — APPROVED** [review]

**Comment by ToddFerris** [comment]
Done.
